### ISSUE TITLE
cdk init fails when no ~/.aws/config present

### ISSUE THREAD

**Issue by kiiadi** [awslabs/aws-cdk#1070]
When I run `cdk init app --language=java` I get the below stack-trace. It should be possible to init an app without any credentials at all, and further it's perfectly valid for the only available credentials to be in a `~/.aws/credentials` file; not all customers use `~/.aws/config`

```bash
Error: ENOENT: no such file or directory, open '/Users/**user**/.aws/config'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:97:26)
    at SharedIniFile.loadFile [as ensureFileLoaded] (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared_ini.js:19:18)
    at SharedIniFile.loadProfile [as getProfile] (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared_ini.js:52:10)
    at Config.region (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/node_loader.js:88:34)
    at Config.set (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/config.js:448:39)
    at Config.<anonymous> (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/config.js:283:12)
    at Config.each (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:485:32)
    at new Config (/Users/**user**/.nvm/versions/node/v8.11.1/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/config.js:282:19)
```

**Comment by kiiadi** [comment]
Upgrading to 0.14.0 fixed this

**Comment by eladb** [comment]
😄

**Comment by eladb** [comment]
Best bug report ever

**Comment by kiiadi** [comment]
😄
