### ISSUE TITLE
Windows setup is broken

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#138]

**Comment by sasaraf** [comment]
Thanks for the lib. looks like great initiative, as we did search for good dev way to deploy CF stacks. following the getting started guide i get the following error (for init App object) on windows. 
Thanks for any lead on this.

software.amazon.jsii.JsiiException: ENOENT: no such file or directory, mkdtemp '/tmp/jsii-kernel-XXXXXX'
Error: ENOENT: no such file or directory, mkdtemp '/tmp/jsii-kernel-XXXXXX'

	at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:118)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:90)
	at software.amazon.jsii.JsiiClient.loadModule(JsiiClient.java:68)
	at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:109)
	at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:106)
	at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:444)
	at software.amazon.awscdk.App.<init>(App.java:16)
	at com.myorg.HelloStackTest.testStack(HelloStackTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by rix0rrr** [comment]
Just found another `/tmp` in the toolkit assets file. Fixing it.

**Comment by sasaraf** [comment]
@eladb thanks for the solving the tmpdir issue. the C:\tmp helps to workaround the above issue. sorry for the delay in response.

I now get a missing module exception related the kernel?
[software.amazon.jsii.JsiiException: Cannot find module '	mpjsii-kernel-VcnlCZ
ode_modules@aws-cdkcx-api'
module.js:549
    throw err;
]

 i didn't find it in the list of requirement in the getting started manual. I guess , once both fixed there will probably be issue with the the clock synchronization between my windows machine to aws as part of the 'signature' of cli commans?, or should i apply chronyc/ntp to solve it. For now i moved to centos 7 instance as i'm in early steps to use your cdk for infrastructure-as-code lib for CF pipeline/deployment for different environment. So the above don't block me , just thought this thread is the right place to target windows issues with the lib. hope ok.

**Comment by eladb** [comment]
@sasaraf Do you still see the issue with cx-api?

**Comment by sasaraf** [comment]
it still has this issue with mpjsii module. couldn't find such module. what npm install should be used for that? (i moved to the latest released cdk maven dependencies 0.8.2, perhaps the fix is in some snapshot version?)

`
Error: Cannot find module '     mpjsii-kernel-2DjNHC
ode_modules@aws-cdkcx-api'
    at Function.Module._resolveFilename (module.js:547:15)
    at Module._load (module.js:474:25)
    at require (C:\Users\siasaraf\AppData\Local\Temp\jsii-java-runtime4231062144825626203\jsii-runtime.js:1:80961)
    at \tmp\jsii-kernel-2DjNHC\node_modules\@aws-cdk\cx-api:1:1
`
