### ISSUE TITLE
cdk installation problem on windows

### ISSUE THREAD

**Issue by sai-tirunagiri** [awslabs/aws-cdk#1567]
Hi,

I did installation on npm on windows. and did the below command
npm install -g aws-cdk

i am having the below problem.

Any pointers on this.

Thanks
```
C:\Users\**********\AppData\Roaming\npm>cdk --version
C:\Users\**********\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.js:27
async function parseCommandLineArguments() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\<user_name>\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk:2:1)
```

**Comment by rix0rrr** [comment]
Could you run `node --version` please?

**Comment by rix0rrr** [comment]
You need at least Node 8.11. NPM should have complained during installation. Did it not?

**Comment by Doug-AWS** [comment]
Please read the [Installing and Configuring the AWS CDK](https://docs.aws.amazon.com/CDK/latest/userguide/install_config.html) section of the CDK user guide.

**Comment by sai-tirunagiri** [comment]
Yup, thanks.. it worked. the problem was with my node version.
