### ISSUE TITLE
Document how to enable source map support

### ISSUE THREAD

**Issue by otterley** [awslabs/aws-cdk#1579]
Currently, when an uncaught exception is encountered when running `cdk`, the backtrace is of the compiled Javascript code, not the TypeScript source.  For example:

```
 cdk synth
/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:305
            throw new Error(`There is already a Construct with name '${childName}' in ${this.toString()}`);
            ^

Error: There is already a Construct with name 'Snapshot Complete' in [object Object]
    at ConstructNode.addChild (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:305:19)
    at new ConstructNode (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:37:24)
    at new Construct (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.js:417:21)
    at new State (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/state.js:10:9)
    at new Task (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.js:14:9)
    at new Snapshotter (/Users/otterley/src/common/snapshotter/lib/index.js:50:30)
    at new DevEnvStack (/Users/otterley/src/aem/dev-env/lib/dev-env-stack.js:17:9)
    at Object.<anonymous> (/Users/otterley/src/aem/dev-env/bin/dev-env.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
```

This is easily remediable by running `require('source-map-support').install();` in the app entry point.

If we do this, we get references to the original source:

```
$ cdk synth

/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:364
      throw new Error(`There is already a Construct with name '${childName}' in ${this.toString()}`);
            ^
Error: There is already a Construct with name 'Snapshot Complete' in [object Object]
    at ConstructNode.addChild (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:364:13)
    at new ConstructNode (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:62:18)
    at new Construct (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/cdk/lib/core/construct.ts:496:17)
    at new State (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/state.ts:152:9)
    at new Task (/Users/otterley/src/common/snapshotter/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task.ts:101:9)
    at new Snapshotter (/Users/otterley/src/common/snapshotter/lib/index.ts:72:22)
    at new DevEnvStack (/Users/otterley/src/aem/dev-env/lib/dev-env-stack.ts:19:5)
    at Object.<anonymous> (/Users/otterley/src/aem/dev-env/bin/dev-env.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
```

**Comment by rix0rrr** [comment]
The following should work:

```
export NODE_OPTIONS="-r source-map-support"
cdk deploy
```

Maybe we can integrate this in a nice way somewhere.
