### ISSUE TITLE
limitation of cidr masks in ec2.VpcNetwork

### ISSUE THREAD

**Issue by mfassisynamedia** [awslabs/aws-cdk#1779]
hi,

I've tried defining this VPCnetwork:

        const vpc = new ec2.VpcNetwork(this, 'TheVPC', {
          cidr: '10.0.0.0/16',
          subnetConfiguration: [
            {
              cidrMask: 17,
              name: 'PublicSubnet',
              subnetType: SubnetType.Public,
            },
            {
              cidrMask: 17,
              name: 'PrivateSubnet',
              subnetType: SubnetType.Private,
            },
          ],
        });

When running cdk deploy, I am getting this error:
/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/network-util.js:120
            throw new Error(`${count} of /${mask} exceeds remaining space of ${this.networkCidr.cidr}`);
            ^

Error: 1 of /17 exceeds remaining space of 10.0.0.0/16
    at NetworkBuilder.addSubnets (/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/network-util.js:120:19)
    at NetworkBuilder.addSubnet (/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/network-util.js:109:21)
    at availabilityZones.forEach (/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/vpc.js:219:48)
    at Array.forEach (<anonymous>)
    at VpcNetwork.createSubnetResources (/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/vpc.js:214:32)
    at VpcNetwork.createSubnets (/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/vpc.js:205:18)
    at new VpcNetwork (/root/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/vpc.js:105:14)
    at new CdkWorkshopStack (/root/cdk-workshop/lib/cdk-workshop-stack.js:9:21)
    at Object.<anonymous> (/root/cdk-workshop/bin/cdk-workshop.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
Subprocess exited with error 1

**Comment by moofish32** [comment]
@mfassisynamedia - by default the VPC will span multiple AZs. So let's assume you have 3 AZs in this region. You are in fact trying to create 6 /17 networks which isn't possible. If you only want 1 public and one private subnet try setting `maxAZs: 1`.

**Comment by mfassisynamedia** [comment]
Got it.

Thank you very much.
