### ISSUE TITLE
Context variable is not found

### ISSUE THREAD

**Issue by spg** [awslabs/aws-cdk#1911]
I am requiring a context variable like so:

```typescript 
this.node.requireContext('env');
const env = this.node.getContext('env');
```

Using aws-cdk 0.25.0, the `env` context variable is not found. Using 0.24.1, this was not an issue:

```
» npx cdk --version
0.25.0 (build 54b5da1)
» npx cdk synth -c env=test

/Users/spgingras/myproject/node_modules/@aws-cdk/cdk/lib/core/construct.ts:243
      throw new Error(`You must supply a context value named '${key}'`);
            ^
Error: You must supply a context value named 'env'
    at ConstructNode.requireContext (/Users/spgingras/myproject/node_modules/@aws-cdk/cdk/lib/core/construct.ts:243:13)
    at new CdkAppStack (/Users/spgingras/myproject/lib/cdk-app-stack.ts:11:15)
    at Object.<anonymous> (/Users/spgingras/myproject/bin/cdk-app.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
Subprocess exited with error 1
» npm i aws-cdk@0.24.1
npm WARN dashboard@0.1.0 No repository field.
npm WARN dashboard@0.1.0 No license field.

+ aws-cdk@0.24.1
added 12 packages from 7 contributors, updated 4 packages and audited 586 packages in 9.536s
found 0 vulnerabilities

» npx cdk --version
0.24.1 (build 67fcf6d)
» npx cdk synth -c env=test
Resources:
[... redacted ...]
```

**Comment by Obirah** [comment]
Same for me!

**Comment by BDQ** [comment]
Confirmed here too, passing context from the CLI is also broken.
