### ISSUE TITLE
CodePipeline: bucketKey is required but shouldn't be

### ISSUE THREAD

**Issue by digitalsanctum** [awslabs/aws-cdk#2167]
I'm trying to specify a S3 bucket without a `bucketKey` as the store for source code store via:

```
val pipelineSourceAction = PipelineSourceAction(PipelineSourceActionProps.builder()
            .withActionName("source_action")
            .withRunOrder(1)
            .withBucket(Bucket.import_(this, "bucket", BucketImportProps.builder().withBucketName("shanetest-bucket").build()))
            .withBucketKey("") // should not end with slash!!!
            .build())
```
I've tried the following:
1. not specifying `withBucketKey`
1. specifying `/` as the key
1. specifying `""` (empty string) as the key

On deploying the stack with the code above, I get the following validation error from CloudFormation:

```
8/9 | 15:55:46 | CREATE_FAILED        | AWS::CodePipeline::Pipeline | pipeline (pipelineDBECAE49) 1 validation error detected: Value '{S3Bucket=shanetest-bucket, S3ObjectKey=}' at 'pipeline.stages.1.member.actions.1.member.configuration' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 1000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: e86d50cc-58b5-4221-bd8e-cd035779bec8)
	new Pipeline (/tmp/jsii-kernel-6Hw0x3/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:48:30)
	\_ obj._wrapSandboxCode (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:6496:49)
	\_ Kernel._wrapSandboxCode (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:6972:20)
	\_ Kernel._create (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:6496:26)
	\_ Kernel.create (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:6249:21)
	\_ KernelHost.processRequest (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:6023:28)
	\_ KernelHost.run (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:5997:14)
	\_ processRequest (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:5997:45)
	\_ promise.then.ret (/tmp/jsii-java-runtime7259556630644295243/jsii-runtime.js:6050:21)
	\_ <anonymous>
```

If I don't specify bucketKey, I get the following validation error from CDK:

```
Exception in thread "main" java.lang.NullPointerException: bucketKey is required
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at software.amazon.awscdk.services.s3.PipelineSourceActionProps$Builder$1.<init>(PipelineSourceActionProps.java:103)
	at software.amazon.awscdk.services.s3.PipelineSourceActionProps$Builder.build(PipelineSourceActionProps.java:101)
	at io.futz.stack.CodeBuildStack.<init>(CodeBuildStack.kt:54)
	at io.futz.MyAppKt.main(MyApp.kt:85)
	at io.futz.MyAppKt.main(MyApp.kt)
```

In the AWS console the bucket key is optional so I expect that I shouldn't have to specify it here.

I'm using latest (0.27.0) version of the CDK.

**Comment by skinny85** [comment]
Hey @digitalsanctum ,

I'm not sure I understand what you're trying to do. The `bucketKey` property points to a ZIP file in your Bucket that will be used as the output of this Action. It is required in the console (see attached screenshot).

What would leaving out `bucketKey` mean in this context?

<img width="1085" alt="Screen Shot 2019-04-02 at 4 15 13 PM" src="https://user-images.githubusercontent.com/460937/55442226-9bc44d00-5562-11e9-992d-73f97d80eed9.png">

**Comment by digitalsanctum** [comment]
Oh my bad. Sorry for the confusion.
