### ISSUE TITLE
Using CfnParameter to give name of existing resources

### ISSUE THREAD

**Issue by vjindalradialtheory** [awslabs/aws-cdk#2467]
We are using ` cdk synth -o cloudformation ` to generate cloud formation templates for our customer . Our Customer have existing vpc and security group. 

We want to use CfnParameter in cloud-formation template so that customer can information for existing vpc and security group while using cloud-formation template .

Here is our code : 

--------------------------------------------------------------------------------

```ts
    const bastionCfParam = new CfnParameter(this, "BastionSecurityGroupId", {
      type: "AWS::EC2::SecurityGroup::Id",
      description: "Bastion Security Group Id"
    });

    return SecurityGroup.import(this, bastionCfParam.stringValue, {
      securityGroupId: this.props.bastionSecurityGroupId
    });
```

--------------------------------------------------------------------------------
We are getting this error  :   

```
/infra/node_modules/@aws-cdk/cdk/lib/construct.ts:87
      throw new Error(`Cannot use tokens in construct ID: ${id}`);
            ^
Error: Cannot use tokens in construct ID: ${Token[BastionSecurityGroupId.Ref.392]}
    at new ConstructNode (/infra/node_modules/@aws-cdk/cdk/lib/construct.ts:87:13)
    at new Construct (/infra/node_modules/@aws-cdk/cdk/lib/construct.ts:598:17)
    at new Resource (/infra/node_modules/@aws-cdk/cdk/lib/resource.ts:14:1)
    at new SecurityGroupBase (/infra/node_modules/@aws-cdk/aws-ec2/lib/security-group.ts:84:5)
    at new Import (/infra/node_modules/@aws-cdk/aws-ec2/lib/security-group.js:158:17)
    at Function.import (/infra/node_modules/@aws-cdk/aws-ec2/lib/security-group.ts:274:12)
    at DataLakeStack.importBastionSecurityGroup (/infra/lib/dataLake-stack.ts:199:32)
    at new DataLakeStack (/infra/lib/dataLake-stack.ts:106:34)
    at Object.<anonymous> (/infra/bin/infra.ts:77:23)
    at Module._compile (module.js:652:30)
```

--------------------------------------------------------------------------------

How can use CfnParameter to give name of existing resources ?

**Comment by eladb** [comment]
The construct ID of the import is not the same as the security group ID (despite the fact that both are called, "id"). Try this and reopen if this doesn't address your issue:

```ts
const bastionCfParam = new CfnParameter(this, "BastionSecurityGroupId", {
  type: "AWS::EC2::SecurityGroup::Id",
  description: "Bastion Security Group Id"
});

return SecurityGroup.import(this, , 'ImportedSecurityGroup', {
  securityGroupId: bastionCfParam.stringValue
});
```
