### ISSUE TITLE
StackOverflowError in Beanstalk configuration

### ISSUE THREAD

**Issue by kianris** [awslabs/aws-cdk#2477]
When creating a Beanstalk environment there are a lot of options to configure, once the list hits a certain amount the CDK command produces a StackOverflowError. It triggers at 88 options in my development environment. This is using Java/Kotlin.

```
import software.amazon.awscdk.App
import software.amazon.awscdk.Stack
import software.amazon.awscdk.services.elasticbeanstalk.CfnEnvironment
import software.amazon.awscdk.services.elasticbeanstalk.CfnEnvironmentProps

class StackOverflowStack(parent: App, id: String = "stack-overflow") : Stack(parent, id) {
    val env = CfnEnvironment(this, "StackOverflowEnvironment", CfnEnvironmentProps.builder()
            .withApplicationName("stack-overflow")
            .withOptionSettings(
                    0.rangeTo(88).map { option("namespace", it.toString(), "value") })
            .build())
}

private fun option(namespace: String, name: String, value: String) =
        CfnEnvironment.OptionSettingProperty.builder()
                .withNamespace(namespace)
                .withOptionName(name)
                .withValue(value)
                .build()
```

Output
```
Exception in thread "main" java.lang.StackOverflowError
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:270)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2746)
	at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:134)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
	at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
	at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
	at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
	at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
       ...
```

**Version:**
 - Ubuntu 18.04
 - Java
 - CDK 0.29.0 (build 2d44ed7)

**Comment by kianris** [comment]
This seems to be a Kotlin issue as re-writing the same thing in Java is working fine.

**Comment by kianris** [comment]
Haven't reproduced in Java, closing.
