### ISSUE TITLE
aws cdk/ecs cluster cant recognise construct

### ISSUE THREAD

**Issue by yujinlim** [awslabs/aws-cdk#2510]
**Describe the bug**
Error on synth and deploy
```
➜  test-cdk git:(master) ✗ npx cdk deploy testDeploymentStack

/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:104
        throw new Error(`No stack could be identified for the construct at path ${_this.path}`);
              ^
Error: No stack could be identified for the construct at path
    at _lookStackUp (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:104:15)
    at ConstructNode.get stack [as stack] (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:97:42)
    at _lookStackUp (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:106:31)
    at ConstructNode.get stack [as stack] (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:97:42)
    at _lookStackUp (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:106:31)
    at ConstructNode.get stack [as stack] (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/construct.ts:97:42)
    at new CfnElement (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/cfn-element.ts:48:33)
    at new CfnRefElement (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/cfn-element.ts:139:1)
    at new CfnResource (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/cdk/lib/cfn-resource.ts:110:5)
    at new CfnCluster (/Users/yujin/Documents/projects/test/test-cdk/node_modules/@aws-cdk/aws-ecs/lib/ecs.generated.ts:78:9)
```

**To Reproduce**
npx cdk synth/deploy testDeploymentStack

**Expected behavior**

**Version:**
 - MacOS
 - Typescpirt
 - CDK Version - 0.31.0 and 0.30.0
 - ECS Version - 0.31.0 and 0.30.0

**Comment by rix0rrr** [comment]
Hi there,

We'd be happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow. If you could please [ask that same question again on StackOverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk) and paste the link to it here, we will answer it for you over there.
