### ISSUE TITLE
Add support for enterprise SSL interception certificates

### ISSUE THREAD

**Issue by mungojam** [awslabs/aws-cdk#2519]
Our company uses SSL interception with their own certificate which is trusted by windows.

When using aws-cdk, this leads to the inevitable error as node doesn't natively use windows cert store:

> ?  Bootstrapping environment ###/eu-west-1...
?  Environment ###/eu-west-1 failed bootstrapping: Error: self signed
certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1260:34)
    at TLSSocket.emit (events.js:196:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at TLSSocket._finishInit (_tls_wrap.js:737:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:569:12) {
  message: 'self signed certificate in certificate chain',
  code: 'NetworkingError',
  region: 'eu-west-1',
  hostname: 'cloudformation.eu-west-1.amazonaws.com',
  retryable: true,
  time: 2019-05-06T16:46:50.195Z
}
self signed certificate in certificate chain

With other tools, we have circumvented this by using either [syswide-cas](https://www.npmjs.com/package/syswide-cas) or [win-ca](https://www.npmjs.com/package/win-ca). VS Code recently integrated a win-ca fork as well so that no longer has the problem.

Please consider adding a similar solution so that we can use CDK internally without having to mess with global environment variables.

I've worked around it for now setting the `NODE_EXTRA_CA_CERTS` environment variable to a snapshot of the certs extracted with `win-ca` but that's not a sustainable approach and would be messy to set up for other devs.

**Comment by nmussy** [comment]
Should this issue be brought to the [AWS SDK for Node repo](https://github.com/aws/aws-sdk-js)? All requests to the AWS are made through the SDK library AFAIK

**Comment by mungojam** [comment]
that's a good point, happy for somebody from aws move it over.

**Comment by nmussy** [comment]
I'm not sure that's possible. You can just open another issue there and reference this one as your use-case.

**Comment by mungojam** [comment]
It is possible 🙂

https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by nmussy** [comment]
TIL! Thanks
