### ISSUE TITLE
keyPolicy: required but missing

### ISSUE THREAD

**Issue by kadishmal** [awslabs/aws-cdk#2717]
**Describe the bug**
`keyPolicy: required but missing` exception is thrown and the CDK application synthesis fails.

**To Reproduce**
```
export class ToolsKeysStack extends Stack {
  constructor(parent: App, id: string, props: ToolsAppStackProps) {
    super(parent, id, props);

    const { DevAccount, ProductionAccount, ProjectName, TestAccount, ToolsAccount } = props;

    const keyPolicy = new PolicyDocument({
      Version: "2012-10-17",
      Id: {
        Ref: "AWS::StackName"
      },
      Statement: [
        {
          Sid: "Allows admin of the key",
          Effect: "Allow",
          Principal: {
            AWS: {
              "Fn::Sub": `arn:aws:iam::${ToolsAccount}:root`
            }
          },
          Action: [
            "kms:Create*",
            "kms:Describe*",
            "kms:Enable*",
            "kms:List*",
            "kms:Put*",
            "kms:Update*",
            "kms:Revoke*",
            "kms:Disable*",
            "kms:Get*",
            "kms:Delete*",
            "kms:ScheduleKeyDeletion",
            "kms:CancelKeyDeletion"
          ],
          Resource: "*"
        },
        {
          Sid: "Allow use of the key by other accounts",
          Effect: "Allow",
          Principal: {
            AWS: [
              {
                "Fn::Sub": `arn:aws:iam::${ProductionAccount}:root`
              },
              {
                "Fn::Sub": `arn:aws:iam::${TestAccount}:root`
              },
              {
                "Fn::Sub": `arn:aws:iam::${DevAccount}:root`
              },
              {
                "Fn::If": [
                  "AddCodeBuildResource",
                  {
                    "Fn::Sub": `arn:aws:iam::${ToolsAccount}:role/${ProjectName}-CodeBuildRole`
                  },
                  {
                    "Ref": "AWS::NoValue"
                  }
                ]
              }
            ]
          },
          Action: [
            "kms:Encrypt",
            "kms:Decrypt",
            "kms:ReEncrypt*",
            "kms:GenerateDataKey*",
            "kms:DescribeKey"
          ],
          Resource: "*"
        }
      ]
    });

    const keyProps: KeyProps = {
      description: 'Used by Assumed Roles in Dev/Test/Prod accounts to Encrypt/Decrypt code',
      enabled: true,
      enableKeyRotation: true,
      policy: keyPolicy
    };

    const key = new Key(this, 'KMSKey', keyProps);

    key.addAlias('alias/codepipeline-crossaccounts');
  }
}
```

Note above that `policy` is being correctly passed. When synthesizing the following exception is throw:

```
$ cdk synthesize --app bin/setup-tools-account.js
/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/runtime.ts:141
      throw new CfnSynthesisError(message);
            ^
Error: Supplied properties not correct for "CfnKeyProps"
  keyPolicy: required but missing
    at ValidationResult.assertSuccess (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/runtime.ts:141:13)
    at cfnKeyPropsToCloudFormation (/Users/user/infrastructure-app/node_modules/@aws-cdk/aws-kms/lib/kms.generated.ts:171:22)
    at CfnKey.renderProperties (/Users/user/infrastructure-app/node_modules/@aws-cdk/aws-kms/lib/kms.generated.js:152:16)
    at PostResolveToken.ret.Resources.util_1.PostResolveToken.props [as processor] (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/cfn-resource.ts:238:33)
    at PostResolveToken.postProcess (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/util.ts:84:17)
    at DefaultTokenResolver.resolveToken (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/resolve.ts:225:20)
    at resolve (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/resolve.ts:124:29)
    at Object.resolve (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/resolve.ts:43:32)
    at resolve (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/resolve.ts:145:36)
    at Object.resolve (/Users/user/infrastructure-app/node_modules/@aws-cdk/cdk/lib/resolve.ts:43:32)
```

**Expected behavior**
Synthesizing should work to generate a CDN template with a KMS key resources.

**Version:**
 - OS: macOS 10.13.6
 - Programming Language: Node.js v10.15.3
 - CDK Version: 0.33

**Comment by kadishmal** [comment]
This is how it did work:

```
export class ToolsKeysStack extends Stack {
  constructor(parent: App, id: string, props: ToolsAppStackProps) {
    super(parent, id, props);

    const { CodeBuildCondition, DevAccount, ProductionAccount, ProjectName, TestAccount, ToolsAccount } = props;

    const usageKeyStatement = new PolicyStatement(PolicyStatementEffect.Allow);

    const usageStatementActions = [
      'kms:Encrypt',
      'kms:Decrypt',
      'kms:ReEncrypt*',
      'kms:GenerateDataKey*',
      'kms:DescribeKey'
    ];

    Fn.sub(`arn:aws:iam::${ProductionAccount}:root`)

    usageKeyStatement
      .addPrincipal(new AccountPrincipal(ProductionAccount))
      .addPrincipal(new AccountPrincipal(TestAccount))
      .addPrincipal(new AccountPrincipal(DevAccount))
      .addActions(...usageStatementActions)
      .addAllResources();

    if (CodeBuildCondition) {
      usageKeyStatement.addPrincipal(new ArnPrincipal(`arn:aws:iam::${ToolsAccount}:role/${ProjectName}-CodeBuildRole`));
    }

    const keyProps: KeyProps = {
      description: 'Used by Assumed Roles in Dev/Test/Prod accounts to Encrypt/Decrypt code',
      enabled: true,
      enableKeyRotation: true
    };

    const key = new Key(this, 'KMSKey', keyProps);

    key.addAlias('alias/codepipeline-crossaccounts');
    key.addToResourcePolicy(usageKeyStatement);
  }
}
```

Seems like it is not possible to simply pass the policy document which would make it much simpler during migration from CFN templates to CDK app.

**Comment by RomainMuller** [comment]
Hey @kadishmal,

Can you try again with `0.35.0` and let us know if the problem persists?

Regards,
Romain.

**Comment by kadishmal** [comment]
It does work! Thanks.
