### ISSUE TITLE
"Cannot find module error" for plugin on cdk bootstrap

### ISSUE THREAD

**Issue by mitchlloyd** [awslabs/aws-cdk#2742]
**Describe the bug**
I have an authentication plugin that runs successfully for all cdk commands except for `cdk bootstrap`. When I run `cdk bootstrap` I get:

```
Unable to resolve plugin cdk-plugin-isengard: Error: Cannot find module 'cdk-plugin-isengard'
Require stack:
- /Users/me/.config/yarn/global/node_modules/aws-cdk/bin/cdk.js
- /Users/me/.config/yarn/global/node_modules/aws-cdk/bin/cdk
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at tryResolve (/Users/me/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:127:24)
    at loadPlugins (/Users/me/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:117:26)
    at initCommandLine (/Users/me/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:135:3)
Unable to resolve plug-in: cdk-plugin-isengard
```

**To Reproduce**
Add a working plugin module in cdk.json. 

```json
{
  "app": "./node_modules/.bin/ts-node bin/cdk.ts",
  "plugin": ["cdk-plugin-isengard"]
}
```

Run

```
yarn cdk bootstrap
```

**Expected behavior**
In previous versions (0.22 at least) the plugin was found. 

**Version:**
 - MacOS 10.13.6
 - TypeScript
 - CDK 0.33.0

**Comment by mitchlloyd** [comment]
This is totally bogus. Just realized that I left off the `yarn` on the command I copied and pasted from the CDK output in a previous step.
