### ISSUE TITLE
CodePipeline throwing Cannot read property 'minInputs' of undefined

### ISSUE THREAD

**Issue by paulfryer** [awslabs/aws-cdk#2799]
**Describe the bug**
When trying to create a CF template for CodePipeline, I'm seeing this exception:

_Amazon.JSII.Runtime.JsiiException: 'Amazon.JSII.Runtime.JsiiException: Cannot read property 'minInputs' of undefined
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Object[] arguments, String methodName)'_

Notice I created a class `SourceAction `which derives from the `Action `class which is abstract. I'm not sure what I'm supposed to do exactly with this derived class I created. The documentation doesn't seem to provide any samples or explanations on what (if anything) the sub class should do?

**To Reproduce**
Command line used or code snippet

*** Program ***
```
   var app = new App(null);
            var buildStack = new CodePipelineStack(app, typeof(CodePipelineStack).Name,
                new StackProps());
            var session = app.Run();
```
*** CodePipeline Stack ***

```
    public class CodePipelineStack : Stack
    {
        public CodePipelineStack(Construct scope, string name, IStackProps props) : base(scope, name, props)
        {
            var codePipeline = new Pipeline(this, "Pipeline", new PipelineProps
            {
            });
            codePipeline.AddStage(new StageAddToPipelineProps
            {
                Name = "SourceStage",
                Actions = new Action[]
                {
                    new SourceAction(new ActionProps
                    {
                        Category = ActionCategory.Source,
                        ActionName = "MySourceAction",
                        Outputs = new[] {new Artifact_("SourceArtifact")},
                        Provider = "CodeCommit"
                    })
                }
            });
            
            codePipeline.AddStage(new StageAddToPipelineProps
            {
                Name = "BuildStage",
                Actions = new Action[]
                {
                    new SourceAction(new ActionProps
                    {
                        Category = ActionCategory.Build,
                        ActionName = "BuildAction",
                        Inputs = new[] {new Artifact_("SourceArtifact")},
                        Provider = "CodeBuild"
                    })
                }
            });
        }
        
        public class SourceAction : Action
        {
            public SourceAction(IActionProps props) : base(props)
            {
                
            }

            protected override void Bind(IActionBind info)
            {
            }
        }
    }
```

**Expected behavior**
I expect the app.Run() command to generate a CloudFormation template.

**Version:**
 - OS: Windows 10
 - Programming Language: .Net Core
 - CDK Version: Latest Nuget as of June 7th

**Comment by paulfryer** [comment]
Looks like this is related to a property on the `Action `class called `ArtifactBound `not being set. If I understand the purpose of this property perhaps we should just default these min and max values to the count that is provided by the Inputs or Outputs array. Why make people provide the bounds if they just provide the inputs and outputs?

**Comment by paulfryer** [comment]
Turns out actions are in a different Nuget package. You have to get the "*.Actions" nuget package.
