### ISSUE TITLE
Upgrading from 0.28.0 to 0.36.0 Amazon.JSII.Runtime.JsiiException: 'Amazon.JSII.Runtime.JsiiException: Resolution error: System.ArgumentException

### ISSUE THREAD

**Issue by kuhnboy** [awslabs/aws-cdk#3066]
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
- Updated nuget packages and npm for cdk from 0.28.0 to 0.36.0
- Create single stack with just a CfnXXX object. In this case I'll use CfnVPC
- Upon app.Synth() and exception is thrown: 

* **What is the expected behavior (or behavior of feature suggested)?**
- CfnXXX objects should be able to be used and app.Synth() would not throw an exception.

* **What is the motivation / use case for changing the behavior or adding this feature?**
- Creating CfnXXX objects worked in previous versions.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Windows 10
  - Language: C#

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Exception upon app.Synth():
Amazon.JSII.Runtime.JsiiException: 'Amazon.JSII.Runtime.JsiiException: Resolution error: System.ArgumentException: Object of type 'Newtonsoft.Json.Linq.JObject' cannot be converted to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeMethod(InvokeRequest request, IReferenceMap referenceMap)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeCallback(Callback callback, IReferenceMap referenceMap, IFrameworkToJsiiConverter converter, String& error).
Object creation stack:
  at new Intrinsic (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\private\intrinsic.js:20:44)
  at new PostResolveToken (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\util.js:72:9)
  at CfnVPC._toCloudFormation (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\cfn-resource.js:167:39)
  at node.addReference.resolve_1.findTokens (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\cfn-element.js:84:77)
  at Object.findTokens (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\private\resolve.js:125:13)
  at CfnVPC.prepare (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\cfn-element.js:84:49)
  at _wrapSandboxCode (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6493:51)
  at Kernel._wrapSandboxCode (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:7126:20)
  at ret._ensureSync (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6493:25)
  at Kernel._ensureSync (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:7097:20)
  at Kernel.invoke (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6492:26)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6186:28)
  at completeCallback (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6159:25)
  at KernelHost.callbackHandler (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6140:16)
  at KernelHost.kernel.jsii_kernel_1.Kernel.cb [as callbackHandler] (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6124:59)
  at CfnVPC.value (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6843:41)
  at Function.prepare (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\construct.js:91:27)
  at Function.synth (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\construct.js:54:14)
  at App.synth (C:\Users\rkuhn\AppData\Local\Temp\jsii-kernel-PIrEOT\node_modules\@aws-cdk\core\lib\app.js:67:52)
  at _wrapSandboxCode (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6493:51)
  at Kernel._wrapSandboxCode (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:7126:20)
  at ret._ensureSync (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6493:25)
  at Kernel._ensureSync (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:7097:20)
  at Kernel.invoke (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6492:26)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6186:28)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at KernelHost.processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6228:16)
  at KernelHost.run (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:14)
  at processRequest (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6132:45)
  at promise.then.val (C:\Users\rkuhn\AppData\Local\Temp\any5x3uv.2ql\jsii-runtime.js:6213:21)
  at <anonymous>
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Object[] arguments, String methodName)
   at Amazon.CDK.CfnElement.Prepare()'

**Comment by kuhnboy** [comment]
Closing due to more specific behavior in https://github.com/awslabs/aws-cdk/issues/3093
