### ISSUE TITLE
java.lang.ClassCastException: software.amazon.awscdk.services.lambda.LambdaRuntime cannot be cast to software.amazon.awscdk.services.lambda.InlinableJavascriptLambdaRuntime

### ISSUE THREAD

**Issue by eranation** [awslabs/aws-cdk#504]
I was trying to create a new Lambda construct, it compiles well but when running cdk synth I'm getting this error: 
```

Exception in thread "main" java.lang.ExceptionInInitializerError
        at ...MyStack.<init>(MyStack.java:25)
        at ..MyApp.<init>(MyApp.java:11)
        at ..MyApp.main(MyApp.java:15)
Caused by: java.lang.ClassCastException: software.amazon.awscdk.services.lambda.LambdaRuntime cannot be cast to software.amazon.awscdk.services.lambda.InlinableJavascriptLambdaRuntime
        at software.amazon.awscdk.services.lambda.LambdaRuntime.<clinit>(LambdaRuntime.java:11)
        ... 3 more

``` 

The code is simply 

```

    Lambda lambda = new Lambda("MyLambda",
        LambdaProps.builder()
            .withCode(LambdaCode.file(...))
            .withHandler(...).withRuntime(LambdaRuntime.JAVA8)
            .build()
```

**Comment by eladb** [comment]
Fix in #505
