### ISSUE TITLE
Bug: toolkit fails to read config/credentials file

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#563]
Stack trace:

```
TypeError: ini.split is not a function
    at Object.string [as parse] (/Users/benisrae/code/cdk-bucket-notifications/aws-cdk/packages/aws-cdk/node_modules/aws-sdk/lib/util.js:197:26)
    at SharedIniFile.ensureFileLoaded (/Users/benisrae/code/cdk-bucket-notifications/aws-cdk/packages/aws-cdk/lib/api/util/sdk_ini_file.ts:49:51)
    at <anonymous>
```

The problem is that the call to `fs.readFile` in [sdk_ini_file.ts](https://github.com/awslabs/aws-cdk/blob/0cbb24708a14ce478ab1053bdaaeb419640d1428/packages/aws-cdk/lib/api/util/sdk_ini_file.ts#L49) returns a `Buffer` and not `string` as expected by `ini.parse`.

**Comment by eladb** [comment]
On it
