### ISSUE TITLE
dotnet: Sample .Net yields (node:9136) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write

### ISSUE THREAD

**Issue by oldnerd** [awslabs/aws-cdk#747]
Starting a new .Net sample application from AWS Dev blog w/
the following three commands

- cdk init app --language dotnet
- dotnet build src
- cdk synth hello-cdk-1

yields these errors on 3 machines - but does yield cloud formation template after this.  Any hints?

`(node:9136) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
    at Object.fs.writeSync (fs.js:735:20)
    at t.SyncStdio.writeBuffer (C:\Users\cleme\AppData\Local\Temp\ksu3fiag.tft\jsii-runtime.js:1:157652)
    at t.SyncStdio.writeLine (C:\Users\cleme\AppData\Local\Temp\ksu3fiag.tft\jsii-runtime.js:1:157195)
    at t.InputOutput.write (C:\Users\cleme\AppData\Local\Temp\ksu3fiag.tft\jsii-runtime.js:1:156645)
    at t.KernelHost.writeError (C:\Users\cleme\AppData\Local\Temp\ksu3fiag.tft\jsii-runtime.js:1:75923)
    at i.then.catch.e (C:\Users\cleme\AppData\Local\Temp\ksu3fiag.tft\jsii-runtime.js:1:75584)
    at <anonymous>
(node:9136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1616) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
    at Object.fs.writeSync (fs.js:735:20)
    at t.SyncStdio.writeBuffer (C:\Users\cleme\AppData\Local\Temp\kfjabsgo.tn2\jsii-runtime.js:1:157652)
    at t.SyncStdio.writeLine (C:\Users\cleme\AppData\Local\Temp\kfjabsgo.tn2\jsii-runtime.js:1:157195)
    at t.InputOutput.write (C:\Users\cleme\AppData\Local\Temp\kfjabsgo.tn2\jsii-runtime.js:1:156645)
    at t.KernelHost.writeError (C:\Users\cleme\AppData\Local\Temp\kfjabsgo.tn2\jsii-runtime.js:1:75923)
    at i.then.catch.e (C:\Users\cleme\AppData\Local\Temp\kfjabsgo.tn2\jsii-runtime.js:1:75584)
    at <anonymous>
(node:1616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by costleya** [comment]
There is a bug with the cli integration invoking the .NET generator. Pending Investigation. Thank you for the report.

**Comment by heshamamin** [comment]
Setting the CDK_OUTDIR environment variable to a valid folder name solved this issue. (Win 10)

**Comment by fulghum** [comment]
https://github.com/awslabs/jsii/issues/341 should have fixed this one.  Let us know if you're still having issues.
