### ISSUE TITLE
NullPointerException when a subclass of Stack has a private method called `name`

### ISSUE THREAD

**Issue by dsilvasc** [awslabs/aws-cdk#757]
repro in scala, but same issue in java:

```scala
object Demo {
  def main(args: Array[String]): Unit = {
    val app = new software.amazon.awscdk.App
    val props = StackProps.builder.withEnv(Environment.builder.withRegion("us-east-1").build()).build()
    val stack: Stack = new Stack(app, "demo", props) {
      private def name: String = "other"
      println(s"name is $name")
    }
    val output = app.synthesizeStack(stack.getName)
    println(output.getTemplate)
  }
}
```

output:

```
name is other
Exception in thread "main" java.lang.NullPointerException: stackName is required
	at java.util.Objects.requireNonNull(Objects.java:228)
	at software.amazon.awscdk.App.synthesizeStack(App.java:55)
	at snapchat.storyvending.cdk.StoryVendingCDKSynthApp$.main(Demo.scala:101)
	at snapchat.storyvending.cdk.StoryVendingCDKSynthApp.main(Demo.scala)
```

bytecode signatures:

```
$ javap -p 'Demo$$anon$1'
Compiled from "Demo.scala"
public final class Demo$$anon$1 extends software.amazon.awscdk.Stack {
  private java.lang.String name();
  public Demo$$anon$1(software.amazon.awscdk.App, software.amazon.awscdk.StackProps);
}
```

Maybe some reflection code is looking for a `name` method in the wrong class (should grab it from Stack or Construct or JsiiObject, not the subclass).

**Comment by rix0rrr** [comment]
@eladb can you figure out why this is?

**Comment by rix0rrr** [comment]
Thanks for reporting. Closing this as it's being tracked elsewhere.
