### ISSUE TITLE
cdk.js, line 30: SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by bnegrao** [awslabs/aws-cdk#808]
Hello,
I just installed the cdk and when I try to execute `cdk init app --language=java` I receive the error message bellow:

```
/usr/local/lib/node_modules/aws-cdk/bin/cdk.js:30
async function parseCommandLineArguments() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/bin/cdk:2:1)
    at Module._compile (module.js:541:32)
``` 
My node is v6.3.0

**Comment by bnegrao** [comment]
Ok, I just realized that async functions is suported by node versions above 7.6

**Comment by eladb** [comment]
👍
