### ISSUE TITLE
The Regex at doesn't allow a trailing +, it only allows the a-zA-Z1-0 etc portion.

### ISSUE THREAD

**Issue by gaffo** [awslabs/aws-cdk#862]
https://github.com/awslabs/aws-cdk/blob/eb4bacfff68a2f2549572c5714057af01c12b7aa/packages/%40aws-cdk/aws-apigateway/lib/resource.ts#L149

This means you can't legally create {proxy+}, which is pretty important in api gateway.

**Comment by rix0rrr** [comment]
I believe we fixed this already?

**Comment by gaffo** [comment]
if (!/^[a-zA-Z0-9\.\_\-]+$/.test(part)) {

doesn't seem like it would work, the only + in there is the repeat for the test pattern.

and it doesn't work on my 0.10.0 version I have on my machine.

**Comment by gaffo** [comment]
My example stack is:

```
import cdk = require('@aws-cdk/cdk');
import apigateway = require('@aws-cdk/aws-apigateway');
import lambda = require('@aws-cdk/aws-lambda');

class MyStack extends cdk.Stack {
    constructor(parent: cdk.App, id: string, props?: cdk.StackProps) {
        super(parent, id, props);

        const lmbda = new lambda.Function(this, "Lambda", {
            code: lambda.Code.inline(`
def handler(a, b):
  return {
    "isBase64Encoded": False,
    "statusCode": 200,
    "headers": { },
    "body": "Hello, world!"
  }
`),
            handler: 'index.handler',
            runtime: lambda.Runtime.Python36,
        });

        const apigw = new apigateway.LambdaIntegration(lmbda, {
            proxy: true,
        });
        const api = new apigateway.RestApi(this, 'api', {
            defaultIntegration: apigw
        });

        api.root.addMethod('ANY');
        const all = api.root.addResource("{proxy+}");
        all.addMethod("ANY");
    }
}

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);

        new MyStack(this, 'hello-cdk', {
        	env: {
        		region: "us-west-2",
                account: "",
        	},
        });
    }
}

process.stdout.write(new MyApp(process.argv).run());
```

If the code is:
```
    if (!/^[a-zA-Z0-9\.\_\-]+$/.test(part)) {
        throw new Error(`Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end: ${part}`);
    }
```

Then I get:

```
C:\Users\gaffo\cdk-test\node_modules\@aws-cdk\aws-apigateway\lib\resource.js:48
        throw new Error(`Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end: ${part}`);
        ^

Error: Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end: proxy+
    at validateResourcePathPart (C:\Users\gaffo\cdk-test\node_modules\@aws-cdk\aws-apigateway\lib\resource.js:48:15)
    at new Resource (C:\Users\gaffo\cdk-test\node_modules\@aws-cdk\aws-apigateway\lib\resource.js:9:9)
    at Object.addResource (C:\Users\gaffo\cdk-test\node_modules\@aws-cdk\aws-apigateway\lib\restapi.js:55:24)
    at new MyStack (C:\Users\gaffo\cdk-test\index.js:29:30)
    at new MyApp (C:\Users\gaffo\cdk-test\index.js:36:9)
    at Object.<anonymous> (C:\Users\gaffo\cdk-test\index.js:44:22)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
```

If I change resource.ts to be:

```
    if (!/^[a-zA-Z0-9\.\_\-]+[\+]+$/.test(part)) {
        throw new Error(`Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end: ${part}`);
    }
```

Then it works fine.

**Comment by rix0rrr** [comment]
Yes, this issue got fixed in https://github.com/awslabs/aws-cdk/pull/769. It's not part of the 0.10.0 release, but will be part of the next release.
